# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firmName', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=10)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firmName', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=300)),
                ('minMarketRate', models.FloatField()),
                ('maxMarketRate', models.FloatField()),
                ('designShare', models.FloatField()),
                ('execShare', models.FloatField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designerPic.Designers')),
            ],
        ),
    ]
