# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designerPic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='point',
            field=models.IntegerField(default=100),
        ),
    ]
