# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designerPic', '0002_designers_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='designerID',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
