# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designerPic', '0005_auto_20161217_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignersProfile',
            new_name='Designers_pro',
        ),
    ]
