# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designerPic', '0007_designers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designers',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
